# Generated by Django 3.2.12 on 2022-07-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='class_field',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='homeroom_teacher_flag',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='minus_point',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(default=None, max_length=11),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='plus_point',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='school',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='subject',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userflag',
            field=models.BooleanField(default=False),
        ),
    ]
