# Generated by Django 3.2.12 on 2022-08-03 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userinfo_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='school',
            field=models.ForeignKey(db_column='school', on_delete=django.db.models.deletion.CASCADE, related_name='school_student', to='accounts.schoolinfo'),
        ),
    ]
