# Generated by Django 3.2.12 on 2022-08-04 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userinfo_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='acc_point',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=45)),
                ('point', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
