# Generated by Django 3.2.12 on 2022-08-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220805_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointlog',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
