# Generated by Django 3.2.12 on 2022-08-05 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_pointlog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointlog',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='point_teacher', to='accounts.userinfo'),
            preserve_default=False,
        ),
    ]
