# Generated by Django 3.2.12 on 2022-08-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userinfo_school'),
        ('accounts', '0008_alter_userinfo_acc_point'),
    ]

    operations = [
    ]
