# Generated by Django 3.2.12 on 2022-08-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userinfo_acc_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profil',
            field=models.ImageField(blank=True, default='', upload_to='accounts/profils'),
            preserve_default=False,
        ),
    ]
