# Generated by Django 3.2.12 on 2022-08-08 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userinfo_school'),
        ('accounts', '0010_alter_userinfo_profil'),
    ]

    operations = [
    ]
