# Generated by Django 3.2.12 on 2022-08-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20220808_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profil',
            field=models.ImageField(blank=True, default='accounts/profils/test01.jpg', upload_to='accounts/profils'),
        ),
    ]
