# Generated by Django 3.2.12 on 2022-08-09 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointshop', '0001_initial'),
        ('accounts', '0012_alter_userinfo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='own_title',
            field=models.ManyToManyField(related_name='title_owner', to='pointshop.Title'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='wear_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pointshop.title'),
        ),
    ]
