# Generated by Django 3.2.12 on 2022-08-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20220808_1039'),
        ('accounts', '0013_auto_20220809_2338'),
    ]

    operations = [
    ]
