# Generated by Django 3.2.12 on 2022-08-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointshop', '0004_icon'),
        ('accounts', '0013_auto_20220809_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='own_icon',
            field=models.ManyToManyField(related_name='icon_owner', to='pointshop.Icon'),
        ),
    ]
