# Generated by Django 3.2.12 on 2022-08-14 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointshop', '0004_icon'),
        ('accounts', '0014_userinfo_own_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='wear_icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pointshop.icon'),
        ),
    ]
