# Generated by Django 3.2.12 on 2022-08-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20220812_1817'),
        ('accounts', '0015_userinfo_wear_icon'),
    ]

    operations = [
    ]
