# Generated by Django 3.2.12 on 2022-08-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_merge_20220814_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointlog',
            name='acc_minus',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pointlog',
            name='acc_point',
            field=models.IntegerField(null=True),
        ),
    ]
