# Generated by Django 3.2.12 on 2022-08-15 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20220814_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointlog',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointlog',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='point_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profil',
            field=models.ImageField(blank=True, default='accounts/profils/profile1.jpg', upload_to='accounts/profils'),
        ),
    ]
