<Find_input1_button2>:
	FloatLayout:
		size: root.width, root.height
		Button: # exit
			on_release:root.onStop()
			pos_hint: {"right":0.98,"top":0.98}
			text:"x"
			bold: True
			color: 1,1,1,1
			size_hint: None, None
			halign:'center'
			valign:'bottom'
			size : 30,30
			background_normal:''
			background_color:0,0,0,0
			canvas.before:
				Color:
					rgba: (1,0,0,1)
				RoundedRectangle:
					size: self.size
					pos : self.pos
					radius:[10]
				Color:
					rgba: 155/255,17/255,30/255,1
				Line:
					width:1
					rounded_rectangle: self.x, self.y, self.width, self.height, 10

		Button: # Home
			on_release:
				app.root.current="login"
				root.manager.transition.direction='down'
			pos_hint: {"right":0.95,"top":0.98}
			text:"Home"
			font_size: 20
			bold: True
			color: 1,1,1,1
			size_hint: None, None
			halign:'center'
			valign:'bottom'
			size : 100,30
			background_normal:''
			background_color:0,0,0,0
			canvas.before:
				Color:
					rgba: 66/255,75/255,90/255,1
				RoundedRectangle:
					size: self.size
					pos : self.pos
					radius:[10]
				Color:
					rgba: 0,0,0,1
				Line:
					width:1
					rounded_rectangle: self.x, self.y, self.width, self.height, 10

		BoxLayout:
			orientation: "vertical"
			size_hint : None, None
			size : 960, 450
			pos_hint : {"center_x":0.5, "center_y":0.5}
			padding: 40
			spacing: 40
			halign:'center'


			Label: # title
                id: title
				text:"Find ID"
				size_hint_y: .8
				color: 94/255,106/255,117/255,1
				font_size : 90
				bold: True
				halign:'center'
				valign:'middle'

			BoxLayout:
				padding:10
				spacing:20
				orientation:"vertical"

				Label: # sub_title
                    id: sub_title
					pos_hint : {"center_x":0.5, "center_y":0.5}
					text:"이름"
					font_size: 40
					bold: True
					color: 0,0,0,1
					

				limitedTextInput:
					id: mid_input ### to get a string							
					multiline: False
					max_input_num :10
					size_hint : .4, None
					pos_hint : {"center_x":0.5, "center_y":0.5}
					font_size: 30
					height:50
					#padding_x:10
					halign:'center'
					#padding_y:(self.height-self.font_size)/2
					background_normal:''
					background_color: (1,1,1,1)
					canvas.before:
						Color:
							rgba: 94/255,106/255,117/255,1
						Line:
							width:1
							rectangle: self.x, self.y, self.width, self.height

			FloatLayout:
				orientation:"horizontal"
				size_hint_y : .4

				Button: # email-btn
                    id:left_btn
					text:"E-mail로 인증"
					bold:True
					font_size: 30
					halign:'center'
					color: 1,1,1,1
					on_press:
						root.leftBtn()
						root.onPopUp()
						app.root.current=root.left_next_page
						root.manager.transition.direction='up'
					size_hint_x : None
					width:300
					pos_hint : {'center_x':.2,'center_y':0}

					background_normal:''
					background_color: (0,0,0,0)
					canvas.before:
						Color:
							rgba :(66/255,75/255,90/255,1)
						RoundedRectangle:
							size: self.size
							pos : self.pos
							radius:[10]					

				Button: # phone-btn
                    id:right_btn
					text:"전화번호로 인증"
					bold:True
					font_size: 30
					halign:'center'
					color: 1,1,1,1
					on_press:
						root.rightBtn()
						root.onPopUp()
						app.root.current=root.right_next_page
						root.manager.transition.direction='up'
					pos_hint : {'center_x':.8,'center_y':0}
					size_hint_x : None
					width:300
					background_normal:''
					background_color: (0,0,0,0)
					canvas.before:
						Color:
							rgba :(66/255,75/255,90/255,1)
						RoundedRectangle:
							size: self.size
							pos : self.pos
							radius:[10]	


