WindowManager:
    Login_Screen:
        name: "login"
    Find_input1_button2: 
        name: "ID_name"
    Find_input2_button2:
        name: "ID_phone"
    Find_input2_button2:
        name: "ID_email"
    Find_input2_button2:
        name: "PW_name"
    Find_input2_button2:
        name: "PW_phone"
    Find_input2_button2:
        name: "PW_email"
    Find_result:
        name: "ID_result"
    Find_result:
        name: "PW_result"
    Find_renew:
        name: "PW_renew"
    ##### Main Screen #####
    Find_result:
        name: "main"
