# Generated by Django 3.2.12 on 2022-08-11 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='quizuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_user', to='chat.quizuser'),
            preserve_default=False,
        ),
    ]
