# Generated by Django 3.2.12 on 2022-08-14 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_quizanswer_quizuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuser',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getuser_byroom', to='chat.quizroom'),
        ),
    ]
