<Login_Screen>:
	FloatLayout:
		size: root.width, root.height
		Button:
			on_release:
				root.manager.onStop()
			pos_hint: {"right":0.98,"top":0.98}
			text:"x"
			bold: True
			color: 1,1,1,1
			size_hint: None, None
			halign:'center'
			valign:'bottom'
			size : 30,30
			background_normal:''
			background_color:0,0,0,0
			canvas.before:
				Color:
					rgba: (1,0,0,1)
				RoundedRectangle:
					size: self.size
					pos : self.pos
					radius:[10]
				Color:
					rgba: 155/255,17/255,30/255,1
				Line:
					width:1
					rounded_rectangle: self.x, self.y, self.width, self.height, 10

		BoxLayout:
			orientation: "vertical"
			size_hint : None, None
			size : 960, 560
			pos_hint : {"center_x":0.5, "center_y":0.5}
			padding: 40
			spacing: 40
			halign:'center'


			BoxLayout:
				orientation:"horizontal"
				size_hint_y : .3

				Label:
					text:"EduColab"
					color: 94/255,106/255,117/255,1
					font_size : 90
					bold: True
					halign:'right'
					valign:'middle'
					
					
				FloatLayout:
					size_hint: (0.1, 1)
					AsyncImage:
						source:'logo.png'
						pos_hint:{'center_x':-1.6,'center_y':.5}
						size_hint: None,None
						size : 150,150

			BoxLayout:
				orientation:"horizontal"
				spacing : 50


				BoxLayout:
					orientation: "vertical"
					size_hint_x: .7
					spacing: 10

					BoxLayout:
						pos_hint : {"x":0, "center_y":0.3}
						size_hint : 1, .3
						
						Label:
							pos_hint : {"center_x":0, "center_y":0.5}
							size_hint : .4, 1
							text:"아이디"
							font_size: 40
							bold: True
							color: 94/255,106/255,117/255,1
							

						limitedTextInput:
							id: ID_input ### to get a string
							multiline: False
							max_input_num :30
							size_hint : .5, .5
							pos_hint : {"center_x":0, "center_y":0.5}
							font_size: 30
							padding:10
							#padding_y:(self.height-self.font_size)/2
							background_normal:''
							background_color: (1,1,1,1)
							canvas.before:
								Color:
									rgba: 94/255,106/255,117/255,1
								Line:
									width:1
									rectangle: self.x, self.y, self.width, self.height


					BoxLayout:
						pos_hint : {"x":0, "center_y":0.7}
						size_hint : 1, .3
						
						Label:
							pos_hint : {"center_x":0, "center_y":0.5}
							size_hint : .4, 1
							text:"비밀번호"
							font_size: 40
							bold: True
							color: 94/255,106/255,117/255,1
							

						limitedTextInput:
							id: PW_input ### to get a string							
							multiline: False
							max_input_num :30
							size_hint : .5, .5
							pos_hint : {"center_x":0, "center_y":0.5}
							font_size: 30
							password:True
							padding:10
							#padding_y:(self.height-self.font_size)/2
							background_normal:''
							background_color: (1,1,1,1)
							canvas.before:
								Color:
									rgba: 94/255,106/255,117/255,1
								Line:
									width:1
									rectangle: self.x, self.y, self.width, self.height



				Button:
					text:"Let's \nColab!"
					font_size: 50
					bold: True
					halign:'center'
					color: 94/255,106/255,117/255,1

					on_release:
						root.loginbtn()
						root.onPopUp()
						app.root.current=root.login_next_page
						root.manager.transition.direction="left"

					pos_hint : {"center_x":0.3, "center_y":0.5}
					size_hint : (.5, .8)
					background_normal:''
					background_color: (0,0,0,0)
					canvas.before:
						Color:
							rgba :(175/255,244/255,198/255,1)
						RoundedRectangle:
							size: self.size
							pos : self.pos
							radius:[40]					
						Color:
							rgba: 156/255,219/255,177/255,1
						Line:
							width:2
							rounded_rectangle: self.x, self.y, self.width, self.height, 40
					

			FloatLayout:
				orientation:"horizontal"
				size_hint_y : .3

				Button:
					text:"ID 찾기"
					bold:True
					font_size: 30
					halign:'center'
					color: 1,1,1,1

					on_release:
						app.root.current="ID_name"
						root.manager.transition.direction="up"

					pos_hint : {"center_x":0.3, "center_y":0.5}
					size_hint : (.3, .8)
					background_normal:''
					background_color: (0,0,0,0)
					canvas.before:
						Color:
							rgba :(66/255,75/255,90/255,1)
						RoundedRectangle:
							size: self.size
							pos : self.pos
							radius:[30]					

				Button:
					text:"PW 찾기"
					bold:True
					font_size: 30
					halign:'center'
					color: 1,1,1,1

					on_release:
						app.root.current="PW_name"
						root.manager.transition.direction="up"

					pos_hint : {"center_x":0.7, "center_y":0.5}
					size_hint : (.3, .8)
					# width:150
					background_normal:''
					background_color: (0,0,0,0)
					canvas.before:
						Color:
							rgba :(66/255,75/255,90/255,1)
						RoundedRectangle:
							size: self.size
							pos : self.pos
							radius:[30]	


# #test for Design
# background_normal:''
# background_color:0,0,0,0
# canvas.before:
# 	Color:
# 		rgba:0,1,0,1
# 	Rectangle: 
# 		size: self.size
# 		pos : self.pos
