# Generated by Django 3.2.12 on 2022-08-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthomework',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='teacherhomework',
            name='deadline',
            field=models.DateField(),
        ),
    ]
