# Generated by Django 3.2.12 on 2022-08-02 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_auto_20220802_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submithomework',
            name='atch_file',
            field=models.FileField(blank=True, upload_to='homework/submit'),
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atch_file_name', models.CharField(default='', max_length=45)),
                ('atch_file', models.FileField(blank=True, upload_to='homework/create')),
                ('student_homework_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.studenthomework')),
                ('teacher_homework_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.teacherhomework')),
            ],
        ),
    ]
