# Generated by Django 3.2.12 on 2022-08-02 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_auto_20220802_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='student_homework_pk',
            new_name='student_homework',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='teacher_homework_pk',
            new_name='teacher_homework',
        ),
        migrations.RenameField(
            model_name='submithomework',
            old_name='student_homework_pk',
            new_name='student_homework',
        ),
        migrations.RenameField(
            model_name='submithomework',
            old_name='teacher_homework_pk',
            new_name='teacher_homework',
        ),
    ]
