# Generated by Django 3.2.12 on 2022-08-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_auto_20220802_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submithomework',
            name='atch_file',
            field=models.FileField(blank=True, null=True, upload_to='homework/submit'),
        ),
        migrations.AlterField(
            model_name='submithomework',
            name='atch_file_name',
            field=models.CharField(default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='submithomework',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='submithomework',
            name='submit_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
