# Generated by Django 3.2.12 on 2022-08-02 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0006_auto_20220802_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthomework',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='S_homework', to=settings.AUTH_USER_MODEL),
        ),
    ]
