# Generated by Django 3.2.12 on 2022-08-03 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0007_alter_studenthomework_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='student_homework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_file', to='homework.studenthomework'),
        ),
        migrations.AlterField(
            model_name='files',
            name='teacher_homework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_file', to='homework.teacherhomework'),
        ),
    ]
