# Generated by Django 3.2.12 on 2022-08-03 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0008_auto_20220803_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenthomework',
            name='check_flag',
        ),
        migrations.AlterField(
            model_name='submithomework',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
