# Generated by Django 3.2.12 on 2022-08-04 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0009_auto_20220803_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthomework',
            name='submit_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teacherhomework',
            name='target',
            field=models.ManyToManyField(related_name='teacher_homework', to=settings.AUTH_USER_MODEL),
        ),
    ]
