<Quiz_Count_Screen>:
	FloatLayout:
		size: root.width, root.height
		Button: # exit
			on_release:
				root.manager.onStop()
				# root.onStop()
			pos_hint: {"right":0.98,"top":0.98}
			text:"x"
			bold: True
			color: 1,1,1,1
			size_hint: None, None
			halign:'center'
			valign:'bottom'
			size : 30,30
			background_normal:''
			background_color:0,0,0,0
			canvas.before:
				Color:
					rgba: (1,0,0,1)
				RoundedRectangle:
					size: self.size
					pos : self.pos
					radius:[10]
				Color:
					rgba: 155/255,17/255,30/255,1
				Line:
					width:1
					rounded_rectangle: self.x, self.y, self.width, self.height, 10

		Button: # Home
			on_release:
				app.root.current="main"
				root.manager.transition.direction=root.next_page_slide
			pos_hint: {"right":0.95,"top":0.98}
			text:"Home"
			font_size: 20
			bold: True
			color: 1,1,1,1
			size_hint: None, None
			halign:'center'
			valign:'bottom'
			size : 100,30
			background_normal:''
			background_color:0,0,0,0
			canvas.before:
				Color:
					rgba: 66/255,75/255,90/255,1
				RoundedRectangle:
					size: self.size
					pos : self.pos
					radius:[10]
				Color:
					rgba: 0,0,0,1
				Line:
					width:1
					rounded_rectangle: self.x, self.y, self.width, self.height, 10

		Button: # Home
			on_release:
				root.next()
			pos_hint: {"right":0.85,"top":0.98}
			text:"넘어가기"
			font_size: 20
			bold: True
			color: 1,1,1,1
			size_hint: None, None
			halign:'center'
			valign:'bottom'
			size: 100,30
			background_normal:''
			background_color:0,0,0,0
			canvas.before:
				Color:
					rgba: 66/255,75/255,90/255,1
				RoundedRectangle:
					size: self.size
					pos : self.pos
					radius:[10]
				Color:
					rgba: 0,0,0,1
				Line:
					width:1
					rounded_rectangle: self.x, self.y, self.width, self.height, 10


		# Button:
		# 	angle:90
		# 	text:"TESTSETSE--A"
		# 	color:0,0,0,1
		# 	size_hint: None, None
		# 	height:150
		# 	width:150
		# 	# background_color:0,0,0,0

		# 	pos_hint: {"center_x":0.5,"center_y":0.4}

		# 	rotate: self.angle

		# 	canvas.before:
		# 		PushMatrix
		# 		Rotate:
		# 			angle: root.angle
		# 			axis: 0,0,1
		# 			origin: root.center
		# 	canvas.after:
		# 		PopMatrix
				

		# 	# Image:
			# 	id:loading
			# 	source: ''
			# 	size:self.parent.size
			# 	center_x:self.parent.center_x
			# 	center_y:self.parent.center_y
				# canvas.before:
				# PushMatrix
				# Rotate:
				# 	axis:0,0,1
				# 	angle:60
				# 	origin:self.center
				# canvas.after:
				# 	PopMatrix


		BoxLayout:
			orientation: "vertical"
			size_hint: None, None
			size: 960, 300
			pos_hint: {"center_x":0.5, "center_y":0.5}
			padding: 40
			spacing: 20
			halign:'center'


			Label: # title
                id:title
				# text:"대기하세요"
				size_hint_y: .8
				color: 94/255,106/255,117/255,1
				font_size: 90
				bold: True
				halign:'center'
				valign:'middle'



# #test for Design
# background_normal:''
# background_color:0,0,0,0
# canvas.before:
# 	Color:
# 		rgba:0,1,0,1
# 	Rectangle: 
# 		size: self.size
# 		pos : self.pos
