# Generated by Django 3.2.12 on 2022-08-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveylist',
            name='class_field',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='surveylist',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
