# Generated by Django 3.2.12 on 2022-08-01 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_surveylist_done_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyquestions',
            old_name='survey_pk',
            new_name='survey',
        ),
        migrations.RemoveField(
            model_name='surveyquestions',
            name='answer',
        ),
    ]
