# Generated by Django 3.2.12 on 2022-08-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20220805_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestionsanswer',
            name='survey_question_pk',
        ),
    ]
