# Generated by Django 3.2.12 on 2022-08-03 05:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0003_rename_survey_question_pk_surveyquestionsanswer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveylist',
            name='done_target',
        ),
        migrations.AddField(
            model_name='surveylist',
            name='done_target',
            field=models.ManyToManyField(related_name='done_target', to=settings.AUTH_USER_MODEL),
        ),
    ]
