# Generated by Django 3.2.12 on 2022-08-03 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0003_auto_20220802_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveylist',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surveyquestions',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_survey', to='survey.surveylist'),
        ),
    ]
