# Generated by Django 3.2.12 on 2022-07-27 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_userinfo_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('classification', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, max_length=10000, null=True)),
                ('atch_data_slp', models.CharField(blank=True, db_column='ATCH_DATA_SLP', max_length=500, null=True)),
                ('atch_file_name', models.CharField(blank=True, db_column='ATCH_FILE_NAME', max_length=300, null=True)),
                ('atch_file_size', models.IntegerField(blank=True, db_column='ATCH_FILE_SIZE', null=True)),
                ('views', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.schoolinfo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
