<<<<<<< HEAD
# Generated by Django 3.2.12 on 2022-07-29 04:37
=======
# Generated by Django 3.2.12 on 2022-08-01 05:40
>>>>>>> afe56c9 (공지사항 메인페이지)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
