# Generated by Django 3.2.12 on 2022-07-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
