# Generated by Django 3.2.12 on 2022-08-03 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_notice_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='atch_file_name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='files',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_file', to='notice.notice'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(),
        ),
    ]
