# Generated by Django 3.2.12 on 2022-08-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointshop', '0003_ptitle_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('content', models.CharField(blank=True, max_length=50)),
                ('icon', models.ImageField(upload_to='pointshop/icon/')),
            ],
        ),
    ]
