<Change_Title_Screen>:
	FloatLayout:
		size: root.width, root.height
		Button: # exit
			on_release:root.manager.onStop()
			pos_hint: {"right":0.98,"top":0.98}
			text:"x"
			bold: True
			color: 1,1,1,1
			size_hint: None, None
			halign:'center'
			valign:'bottom'
			size : 30,30
			background_normal:''
			background_color:0,0,0,0
			canvas.before:
				Color:
					rgba: (1,0,0,1)
				RoundedRectangle:
					size: self.size
					pos : self.pos
					radius:[10]
				Color:
					rgba: 155/255,17/255,30/255,1
				Line:
					width:1
					rounded_rectangle: self.x, self.y, self.width, self.height, 10

		Button: # Home
			on_release:
				app.root.current="main"
				root.manager.transition.direction='up'
			pos_hint: {"right":0.95,"top":0.98}
			text:"Home"
			font_size: 20
			bold: True
			color: 1,1,1,1
			size_hint: None, None
			halign:'center'
			valign:'bottom'
			size : 100,30
			background_normal:''
			background_color:0,0,0,0
			canvas.before:
				Color:
					rgba: 66/255,75/255,90/255,1
				RoundedRectangle:
					size: self.size
					pos : self.pos
					radius:[10]
				Color:
					rgba: 0,0,0,1
				Line:
					width:1
					rounded_rectangle: self.x, self.y, self.width, self.height, 10

		BoxLayout:
			orientation: "vertical"
			size_hint : None, None
			size : 960, 640
			pos_hint : {"center_x":0.5, "center_y":0.5}
			padding: 40
			spacing: 40
			halign:'center'


			Label: # title
                id:title
				text: "칭호 변경"
				size_hint_y: None
				height:70
				color: 94/255,106/255,117/255,1
				font_size: 60
				bold: True
				halign:'center'
				valign:'middle'

			ScrollView:
				size_hint: 1, 1
				pos_hint:{"center_x":0.5,"top":1}
				bar_inactive_color: 0,0,0,0.5

				bar_color: root.key_color
				bar_width:20
				scroll_type:['bars','content']

				GridLayout:
					id:grid
					size_hint: 1, None
					height: self.minimum_height
					cols:2
					pos_hint:{"center_x":1,"top":1}
					padding:20
					spacing:20
					#test for Design
					background_normal:''
					background_color:0,0,0,0
					canvas.before:
						Color:
							rgba:218/255,220/255,222/255,1
						Rectangle: 
							size: self.size
							pos: self.pos

					# CheckBox:
					# 	id:ans1
					# 	group:"ans"
					# 	pos_hint:{"center_y":0.5}
					# 	# pos_hint:{"center_x":0.5,"top":1}
					# 	size_hint: None, None

					# 	height:45
					# 	width:45

					# 	background_normal:''
					# 	backgournd_color:0,0,0,0

					# 	#test for Design
					# 	canvas.before:
					# 		# Color:
					# 		# 	rgba:1,1,1,1
					# 		# Rectangle: 
					# 		# 	size: self.width+self.parent.width-85, self.height+10
					# 		# 	pos: self.x, self.y-5
					# 		Color:
					# 			rgba:1,1,1,1
					# 		RoundedRectangle: 
					# 			size: 26, 26
					# 			pos: self.x+(self.width/2)-13, self.y+(self.height/2)-13
					# 			radius:[13]
					# 		Color:
					# 			rgba: 145/255,157/255,167/255,1
					# 		Line:
					# 			width:2
					# 			rounded_rectangle: self.x+(self.width/2)-7, self.y+(self.height/2)-7, 14, 14, 7

					# Label:
					# 	id:content
					# 	# pos_hint:{"center_x":0.5,"top":1}
					# 	size_hint: 1, None
					# 	bold: True
					# 	text_size:self.width-45,None
					# 	font_size:40
					# 	height: self.texture_size[1]
					# 	halign:"left"
					# 	valign:"top"
					# 	color:0,0,0,1
						
					# 	background_normal:''
					# 	backgournd_color:0,0,0,0

					# 	#test for Design
					# 	canvas.before:
					# 		Color:
					# 			rgba:1,1,1,1
					# 		Rectangle: 
					# 			size: self.width, self.height+10
					# 			pos: self.x, self.y-5
					
			Button: # email-btn
				text:"저장"
				bold:True
				font_size: 30
				halign:'center'
				color: 1,1,1,1
				on_release:
					root.save_title()
					root.go_next()
				size_hint: None,None
				width:300
				height:50
				pos_hint: {'center_x':.5,'center_y':.5}

				background_normal:''
				background_color: (0,0,0,0)
				canvas.before:
					Color:
						rgba:(66/255,75/255,90/255,1)
					RoundedRectangle:
						size: self.size
						pos: self.pos
						radius:[10]					

<Temp_checkbox>:
	group:"ans"
	pos_hint:{"center_y":0.5}
	# pos_hint:{"center_x":0.5,"top":1}
	size_hint: None, None
	# ans_num:0
	height:45
	width:45
	background_normal:''
	backgournd_color:0,0,0,0
	on_active: app.root.get_screen("Change_title").checkbox_click(self, self.active, self.ans_num)

	#test for Design
	canvas.before:
		# Color:
		# 	rgba:1,1,1,1
		# Rectangle: 
		# 	size: self.width+self.parent.width-85, self.height+10
		# 	pos: self.x, self.y-5
		Color:
			rgba:1,1,1,1
		RoundedRectangle: 
			size: 26, 26
			pos: self.x+(self.width/2)-13, self.y+(self.height/2)-13
			radius:[13]
		Color:
			rgba: 145/255,157/255,167/255,1
		Line:
			width:2
			rounded_rectangle: self.x+(self.width/2)-7, self.y+(self.height/2)-7, 14, 14, 7

<Temp_button>:
	size_hint: 1, None
	bold: True
	text_size:self.width-45,None
	font_size:40
	height: self.texture_size[1]
	halign:"left"
	valign:"top"
	color:0,0,0,1
	on_release:app.root.get_screen("Change_title").toggle_btn(self.ans_num)
	
	background_normal:''
	background_down:''
	backgournd_color:0,0,0,0

	#test for Design
	canvas.before:
		Color:
			rgba:1,1,1,1
		Rectangle: 
			size: self.width, self.height+10
			pos: self.x, self.y-5
# #test for Design
# background_normal:''
# background_color:0,0,0,0
# canvas.before:
# 	Color:
# 		rgba:0,1,0,1
# 	Rectangle: 
# 		size: self.size
# 		pos : self.pos
