WindowManager:
    Loading_Screen:
        name: 'loading'
    Login_Screen:
        name: "login"
    Find_input1_button1: 
        name: "ID_name"
    Find_input2_button2:
        name: "ID_email"
    Find_input2_button1:
        name: "PW_name"
    Find_input2_button2:
        name: "PW_email"
    Find_result:
        name: "ID_result"
    Find_result:
        name: "PW_result"
    Find_renew:
        name: "PW_renew"
    ##### Main Screen #####
    Main_Screen:
        name: "main"
    List_Screen:
        name: "Notice_list1" #좌우 이동용
    List_Screen:
        name: "Notice_list2" #좌우 이동용
    List_Screen:
        name: "Memo_list1" #좌우 이동용
    List_Screen:
        name: "Memo_list2" #좌우 이동용
    Quiz_Start_Screen:
        name: "Quiz_list1"
    List_Screen:
        name: "Survey_list1" #좌우 이동용
    List_Screen:
        name: "Survey_list2" #좌우 이동용
    Info_Screen:
        name: "Notice_info"
    ##### Survey Screen #####
    Survey_Select_Screen:
        name: "Survey_select1" #좌우 이동용
    Survey_Select_Screen:
        name: "Survey_select2" #좌우 이동용
    Survey_Word_Screen:
        name: "Survey_word1" #좌우 이동용
    Survey_Word_Screen:
        name: "Survey_word2" #좌우 이동용

    Quiz_Waiting_Screen:
        name: "Quiz_wait"
    Quiz_Count_Screen:
        name: "Quiz_count"
    Quiz_Select_Screen:
        name: "Quiz_select"
    Quiz_Result_Screen:
        name: "Quiz_result"

    Change_Title_Screen:
        name: "Change_title"