# Generated by Django 3.2.12 on 2022-08-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_rename_data_event_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeLine',
        ),
    ]
