<List_Screen>:
	FloatLayout:
		size: root.width, root.height
		Button:
			on_release:
				root.manager.onStop()
			pos_hint: {"right":0.98,"top":0.98}
			text:"x"
			bold: True
			color: 1,1,1,1
			size_hint: None, None
			halign:'center'
			valign:'bottom'
			size : 30,30
			# background_normal:''
			background_color:0,0,0,0
			canvas.before:
				Color:
					rgba: 1,0,0,1
				RoundedRectangle:
					size: self.size
					pos: self.pos
					radius:[10]
				Color:
					rgba: 155/255,17/255,30/255,1
				Line:
					width:1
					rounded_rectangle: self.x, self.y, self.width, self.height, 10

		Button: # Home
			on_release:
				root.page_num_reset()
				app.root.current="main"
				root.manager.transition.direction='down'
			pos_hint: {"right":0.95,"top":0.98}
			text:"Main"
			font_size: 20
			bold: True
			color: 1,1,1,1
			size_hint: None, None
			halign:'center'
			valign:'bottom'
			size : 100,30
			background_normal:''
			background_color:0,0,0,0
			canvas.before:
				Color:
					rgba: 66/255,75/255,90/255,1
				RoundedRectangle:
					size: self.size
					pos : self.pos
					radius:[10]
				Color:
					rgba: 0,0,0,1
				Line:
					width:1
					rounded_rectangle: self.x, self.y, self.width, self.height, 10


		BoxLayout:
			orientation: "vertical"
			size_hint : None, None
			size : 1040, 700
			pos_hint : {"center_x":0.5, "center_y":0.5}
			padding: 40
			spacing: 30
			halign:'center'


			BoxLayout:
				orientation:"horizontal"
				size_hint_y : None
				height:140

				Label:
					id:main_title
					# text:"공지사항"
					color: 94/255,106/255,117/255,1
					font_size : 90
					bold: True
					# halign:'right'
					valign:'middle'

			BoxLayout:
				orientation:"vertical"
				spacing: 2
				padding: 2
				# #test for Design
				background_normal:''
				background_color:0,0,0,0
				canvas.before:
					Color:
						rgba:218/255,220/255,222/255,1
					Rectangle: 
						size: self.size
						pos: self.pos
				canvas.after:
					Color:
						rgba: root.key_color
					Line:
						width:3
						points:(self.x+3, self.y+self.height, self.x+self.width-3, self.y+self.height)
				
				BoxLayout:
					orientation:"horizontal"
					spacing: 2
					# padding: 2

					Label: #번호
						text_size: self.size
						text:"번호"
						halign:"center"
						valign:"middle"
						color: 144/255,144/255,144/255,1
						font_size:25
						size_hint_x: None
						width: 100
						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:245/255,245/255,245/255,1
							Rectangle: 
								size: self.size
								pos: self.pos			
					Label: #제목
						text_size: self.size
						text:"제목"
						halign:"center"
						valign:"middle"
						color: 144/255,144/255,144/255,1
						font_size:25
						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:245/255,245/255,245/255,1
							Rectangle: 
								size: self.size
								pos: self.pos	
					Label: # 작성자
						text_size: self.size
						text:"작성자"
						halign:"center"
						valign:"middle"
						color: 144/255,144/255,144/255,1
						font_size:25
						size_hint_x: None
						width: 110
						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:245/255,245/255,245/255,1
							Rectangle: 
								size: self.size
								pos: self.pos	
					Label: #작성일
						text_size: self.size
						text:"작성날짜"
						halign:"center"
						valign:"middle"
						color: 144/255,144/255,144/255,1
						font_size:25
						size_hint_x: None
						width: 200
						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:245/255,245/255,245/255,1
							Rectangle: 
								size: self.size
								pos: self.pos			

				BoxLayout:
					orientation:"horizontal"
					spacing: 2
					# padding: 2

					Button: #번호
						id:num1
						text_size: self.size
						# text:"num1" ## 6자리가 한계
						halign:"center"
						valign:"middle"
						color: 144/255,144/255,144/255,1
						font_size:25
						size_hint_x: None
						width: 100

						on_release:
							root.content_btn(1)
							root.manager.before_page=root.name
							# print(root.content_page)
							app.root.current=root.content_page
							root.manager.transition.direction="up"

						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:245/255,245/255,245/255,1
							Rectangle: 
								size: self.size
								pos: self.pos			
					Button: #제목
						id:title1
						text_size: self.size
						# text:"title1"
						halign:"center"
						valign:"middle"
						color: 0,0,0,1
						font_size:25

						on_release:
							root.content_btn(1)
							root.manager.before_page=root.name
							# print(root.content_page)
							app.root.current=root.content_page
							root.manager.transition.direction="up"

						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:1,1,1,1
							Rectangle: 
								size: self.size
								pos: self.pos	
					Button: # 작성자
						id:writer1
						text_size: self.size
						# text:"writer1"
						halign:"center"
						valign:"middle"
						color: 0,0,0,1
						font_size:25
						size_hint_x: None
						width: 110

						on_release:
							root.content_btn(1)
							root.manager.before_page=root.name
							# print(root.content_page)
							app.root.current=root.content_page
							root.manager.transition.direction="up"

						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:1,1,1,1
							Rectangle: 
								size: self.size
								pos: self.pos	
					Button: #작성일
						id:date1
						text_size: self.size
						# text:"date1"
						halign:"center"
						valign:"middle"
						color: 0,0,0,1
						font_size:25
						size_hint_x: None
						width: 200

						on_release:
							root.content_btn(1)
							root.manager.before_page=root.name
							# print(root.content_page)
							app.root.current=root.content_page
							root.manager.transition.direction="up"

						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:1,1,1,1
							Rectangle: 
								size: self.size
								pos: self.pos
				BoxLayout:
					orientation:"horizontal"
					spacing: 2
					# padding: 2

					Button: #번호
						id:num2
						text_size: self.size
						# text:"num2" ## 6자리가 한계
						halign:"center"
						valign:"middle"
						color: 144/255,144/255,144/255,1
						font_size:25
						size_hint_x: None
						width: 100

						on_release:
							root.content_btn(2)
							root.manager.before_page=root.name
							app.root.current=root.content_page
							root.manager.transition.direction="up"

						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:245/255,245/255,245/255,1
							Rectangle: 
								size: self.size
								pos: self.pos			
					Button: #제목
						id:title2
						text_size: self.size
						# text:"title2"
						halign:"center"
						valign:"middle"
						color: 0,0,0,1
						font_size:25

						on_release:
							root.content_btn(2)
							root.manager.before_page=root.name
							app.root.current=root.content_page
							root.manager.transition.direction="up"

						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:1,1,1,1
							Rectangle: 
								size: self.size
								pos: self.pos	
					Button: # 작성자
						id:writer2
						text_size: self.size
						# text:"writer2"
						halign:"center"
						valign:"middle"
						color: 0,0,0,1
						font_size:25
						size_hint_x: None
						width: 110

						on_release:
							root.content_btn(2)
							root.manager.before_page=root.name
							app.root.current=root.content_page
							root.manager.transition.direction="up"

						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:1,1,1,1
							Rectangle: 
								size: self.size
								pos: self.pos	
					Button: #작성일
						id:date2
						text_size: self.size
						# text:"date2"
						halign:"center"
						valign:"middle"
						color: 0,0,0,1
						font_size:25
						size_hint_x: None
						width: 200

						on_release:
							root.content_btn(2)
							root.manager.before_page=root.name
							app.root.current=root.content_page
							root.manager.transition.direction="up"

						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:1,1,1,1
							Rectangle: 
								size: self.size
								pos: self.pos
				BoxLayout:
					orientation:"horizontal"
					spacing: 2
					# padding: 2

					Button: #번호
						id:num3
						text_size: self.size
						# text:"num3" ## 6자리가 한계
						halign:"center"
						valign:"middle"
						color: 144/255,144/255,144/255,1
						font_size:25
						size_hint_x: None
						width: 100

						on_release:
							root.content_btn(3)
							root.manager.before_page=root.name
							app.root.current=root.content_page
							root.manager.transition.direction="up"

						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:245/255,245/255,245/255,1
							Rectangle: 
								size: self.size
								pos: self.pos			
					Button: #제목
						id:title3
						text_size: self.size
						# text:"title3"
						halign:"center"
						valign:"middle"
						color: 0,0,0,1
						font_size:25

						on_release:
							root.content_btn(3)
							root.manager.before_page=root.name
							app.root.current=root.content_page
							root.manager.transition.direction="up"

						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:1,1,1,1
							Rectangle: 
								size: self.size
								pos: self.pos	
					Button: # 작성자
						id:writer3
						text_size: self.size
						# text:"writer3"
						halign:"center"
						valign:"middle"
						color: 0,0,0,1
						font_size:25
						size_hint_x: None
						width: 110

						on_release:
							root.content_btn(3)
							root.manager.before_page=root.name
							app.root.current=root.content_page
							root.manager.transition.direction="up"

						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:1,1,1,1
							Rectangle: 
								size: self.size
								pos: self.pos	
					Button: #작성일
						id:date3
						text_size: self.size
						# text:"date3"
						halign:"center"
						valign:"middle"
						color: 0,0,0,1
						font_size:25
						size_hint_x: None
						width: 200

						on_release:
							root.content_btn(3)
							root.manager.before_page=root.name
							app.root.current=root.content_page
							root.manager.transition.direction="up"

						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:1,1,1,1
							Rectangle: 
								size: self.size
								pos: self.pos
				BoxLayout:
					orientation:"horizontal"
					spacing: 2
					# padding: 2

					Button: #번호
						id:num4
						text_size: self.size
						# text:"num4" ## 6자리가 한계
						halign:"center"
						valign:"middle"
						color: 144/255,144/255,144/255,1
						font_size:25
						size_hint_x: None
						width: 100

						on_release:
							root.content_btn(4)
							root.manager.before_page=root.name
							app.root.current=root.content_page
							root.manager.transition.direction="up"

						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:245/255,245/255,245/255,1
							Rectangle: 
								size: self.size
								pos: self.pos			
					Button: #제목
						id:title4
						text_size: self.size
						# text:"title4"
						halign:"center"
						valign:"middle"
						color: 0,0,0,1
						font_size:25

						on_release:
							root.content_btn(4)
							root.manager.before_page=root.name
							app.root.current=root.content_page
							root.manager.transition.direction="up"
						
						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:1,1,1,1
							Rectangle: 
								size: self.size
								pos: self.pos	
					Button: # 작성자
						id:writer4
						text_size: self.size
						# text:"writer4"
						halign:"center"
						valign:"middle"
						color: 0,0,0,1
						font_size:25
						size_hint_x: None
						width: 110

						on_release:
							root.content_btn(4)
							root.manager.before_page=root.name
							app.root.current=root.content_page
							root.manager.transition.direction="up"

						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:1,1,1,1
							Rectangle: 
								size: self.size
								pos: self.pos	
					Button: #작성일
						id:date4
						text_size: self.size
						# text:"date4"
						halign:"center"
						valign:"middle"
						color: 0,0,0,1
						font_size:25
						size_hint_x: None
						width: 200

						on_release:
							root.content_btn(4)
							root.manager.before_page=root.name
							app.root.current=root.content_page
							root.manager.transition.direction="up"

						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:1,1,1,1
							Rectangle: 
								size: self.size
								pos: self.pos

				BoxLayout:
					orientation:"horizontal"
					spacing: 2
					# padding: 2

					Button: #번호
						id:num5
						text_size: self.size
						# text:"num5" ## 6자리가 한계
						halign:"center"
						valign:"middle"
						color: 144/255,144/255,144/255,1
						font_size:25
						size_hint_x: None
						width: 100

						on_release:
							root.content_btn(5)
							root.manager.before_page=root.name
							app.root.current=root.content_page
							root.manager.transition.direction="up"

						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:245/255,245/255,245/255,1
							Rectangle: 
								size: self.size
								pos: self.pos			
					Button: #제목
						id:title5
						text_size: self.size
						# text:"title5"
						halign:"center"
						valign:"middle"
						color: 0,0,0,1
						font_size:25

						on_release:
							root.content_btn(5)
							root.manager.before_page=root.name
							app.root.current=root.content_page
							root.manager.transition.direction="up"

						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:1,1,1,1
							Rectangle: 
								size: self.size
								pos: self.pos	
					Button: # 작성자
						id:writer5
						text_size: self.size
						# text:"writer5"
						halign:"center"
						valign:"middle"
						color: 0,0,0,1
						font_size:25
						size_hint_x: None
						width: 110

						on_release:
							root.content_btn(5)
							root.manager.before_page=root.name
							app.root.current=root.content_page
							root.manager.transition.direction="up"

						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:1,1,1,1
							Rectangle: 
								size: self.size
								pos: self.pos	
					Button: #작성일
						id:date5
						text_size: self.size
						# text:"date5"
						halign:"center"
						valign:"middle"
						color: 0,0,0,1
						font_size:25
						size_hint_x: None
						width: 200

						on_release:
							root.content_btn(5)
							root.manager.before_page=root.name
							app.root.current=root.content_page
							root.manager.transition.direction="up"

						# #test for Design
						background_normal:''
						background_color:0,0,0,0
						canvas.before:
							Color:
								rgba:1,1,1,1
							Rectangle: 
								size: self.size
								pos: self.pos

			BoxLayout:
				orientation:"horizontal"
				pos_hint:{"center_x":0.5,"center_y":0.5}
				size_hint:0.6,None
				height:70
				spacing: 20

				Button:
					size_hint_x:None
					width:70
					background_color:0,0,0,0
					on_release:
						root.next_flag_setup("before")
						root.next_page_setup("start")
						app.root.current=root.next_page
						root.manager.transition.direction="right"
					Image:
						id:before2
						source: ''
						size:self.parent.size
						center_x:self.parent.center_x
						center_y:self.parent.center_y

				Button:
					size_hint_x:None
					width:70
					background_color:0,0,0,0
					on_release:
						root.next_flag_setup("before")
						root.next_page_setup("")
						app.root.current=root.next_page
						root.manager.transition.direction="right"
					Image:
						id:before1
						source: ''
						size:self.parent.size
						center_x:self.parent.center_x
						center_y:self.parent.center_y

				Label:
					id:middle
					# text:"1 / 70"
					bold:True
					font_size:30
					color:root.key_color
					# #test for Design
					background_normal:''
					background_color:0,0,0,0
					canvas.before:
						Color:
							rgba: 1,1,1,1
						RoundedRectangle:
							size: self.size
							pos: self.pos
							radius:[35]					
						Color:
							rgba: root.key_color
						Line:
							width:2
							rounded_rectangle: self.x, self.y, self.width, self.height, 35
				Button:
					size_hint_x:None
					width:70
					background_color:0,0,0,0
					on_release:
						root.next_flag_setup("after")
						root.next_page_setup('')
						app.root.current=root.next_page
						root.manager.transition.direction="left"
					Image:
						id:after1
						source: ''
						size:self.parent.size
						center_x:self.parent.center_x
						center_y:self.parent.center_y

				Button:
					size_hint_x:None
					width:70
					background_color:0,0,0,0
					on_release:
						root.next_flag_setup("after")
						root.next_page_setup("end")
						app.root.current=root.next_page
						root.manager.transition.direction="left"
					Image:
						id:after2
						source: ''
						size:self.parent.size
						center_x:self.parent.center_x
						center_y:self.parent.center_y


# #test for Design
# background_normal:''
# background_color:0,0,0,0
# canvas.before:
# 	Color:
# 		rgba:0,1,0,1
# 	Rectangle: 
# 		size: self.size
# 		pos : self.pos
